name: Create GitHub release page

on:
  push:
    branches:
      - 'create-release-**'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | tr '/' ' ' | awk '{print $3}')
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Delete tag if exists
        run: |
          if [ $(git tag -l "${{ env.BRANCH_NAME }}") ]; then
              git push --delete origin tags/${{ env.BRANCH_NAME }}
          fi

      - name: Create tag
        run: |
          git tag ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}

      - name: Crete Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.BRANCH_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true

      - name: echo
        run: echo "end"
