name: Create GitHub release page

on:
  push:
    branches:
      - 'create-release-**'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | tr '/' ' ' | awk '{print $3}')
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Delete tag if exists
        run: git push --delete origin tags/${{ env.BRANCH_NAME }} > /dev/null 2>&1

      - name: Create tag
        run: |
          git tag ${{ env.BRANCH_NAME }}
          git push origin tags/${{ env.BRANCH_NAME }}

      - name: Crete Release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ env.BRANCH_NAME }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#          allowUpdates: true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.BRANCH_NAME }}
          release_name: ${{ env.BRANCH_NAME }}

      - name: echo
        run: echo "end"
