name: Enable Auto Merge

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: enabled auto merge?
        id: auto-merge
        run: |
          ENABLED_AUTO_MERGE=$(gh pr view ${{github.event.pull_request.number}} --json autoMergeRequest | jq ".autoMergeRequest != null")
          echo "enabled=${ENABLED_AUTO_MERGE}" >> $GITHUB_OUTPUT

      - name: execute tasks
        if: steps.auto-merge.outputs.enabled == 'false'
        run: |
          gh pr merge ${{github.event.pull_request.number}} --auto
