name: Enable Auto Merge

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: enabled auto merge?
        id: auto-merge
        run: |
          ENABLED_AUTO_MERGE=$(gh pr view ${{github.event.pull_request.number}} --json autoMergeRequest | jq ".autoMergeRequest != null")
          echo "enabled=${ENABLED_AUTO_MERGE}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: execute tasks
        if: steps.auto-merge.outputs.enabled == 'false'
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"auto_merge": true}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{github.event.pull_request.number}}
