name: Read secret values

on:
  workflow_dispatch:

jobs:
  read-secret:
    name: Read secret values
    runs-on: ubuntu-latest

    steps:
      - name: echo
        env:
          THIS_IS_VARIABLE: ${{ vars.THIS_IS_VARIABLE }}
          TEST_LOG_KIT_TOKEN: ${{ secrets.TEST_LOG_KIT_TOKEN }}
          THIS_IS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${THIS_IS_VARIABLE}"
          echo "${TEST_LOG_KIT_TOKEN}"
          echo "${THIS_IS_GITHUB_TOKEN}"
