name: Read secret values

on:
  workflow_dispatch:

jobs:
  read-secret:
    name: Read secret values
    runs-on: ubuntu-latest

    steps:
      - name: echo
        env:
          THIS_IS_SECRET: ${{ secrets.THIS_IS_SECRET }}
          THIS_IS_VARIABLE: ${{ var.THIS_IS_VARIABLE }}
          THIS_IS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${THIS_IS_SECRET}"
          echo "${THIS_IS_VARIABLE}"
          echo "${THIS_IS_GITHUB_TOKEN}"
